version: '3.1'
services:
  app:
    container_name: dogmates-app
    image: dogmates-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=dogmates

