version: '3.6'
services:
  # backend server
  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
      target: finalApp
    container_name: pawmates-server
    image: pawmates-server
    ports:
      - 8090:8090
    networks:
      - serverclient

  # frontend client
  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    container_name: pawmates-client
    image: pawmates-client
    ports:
      -  8080:8080
    depends_on:
      - server
    networks:
      - serverclient

networks:
  serverclient:
    driver: bridge