version: '3.6'
services:
  # database
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=dogmates
    networks:
      - serverdb

  # backend server
  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
      target: finalApp
    container_name: pawmates-server
    image: pawmates-server
    ports:
      - 8090:8090
    depends_on:
      - db
    networks:
      - serverdb
      - serverclient

  # frontend client
  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    container_name: pawmates-client
    image: pawmates-client
    ports:
      -  8080:8080
    depends_on:
      - server
    networks:
      - serverclient

networks:
  serverdb:
    driver: bridge
  serverclient:
    driver: bridge